
server:
  port: ${PORT:8083}
  servlet: 
    context-path: ${SERVLET_CONTEXT_PATH:/}
    
spring:
  application:
    name: security-service
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:localhost}:${DB_PORT:3096}/${DB_NAME:demo}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:user1}
    password: ${DB_PASSWORD:passw0rd!}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1   
      
#MyBatis
mybatis:
    mapper-locations: classpath:mybatis/mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true       